name: Deploy to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/iris-streamlit:latest
        docker build -t $IMAGE .
        docker push $IMAGE